### ISSUE TITLE
Unable to update to latest ruby-lsp 0.22.0 with this gem installed

### ISSUE THREAD

**Issue by bananastalktome** [Shopify/ruby-lsp-rails#532]
With this gem installed, I am unable to update `ruby-lsp` to the latest 0.22.0 release since ruby-lsp-rails is pinned to ruby-lsp versions `(>= 0.21.2, < 0.22.0)`. I know 0.22.0 was just released earlier today, but I wanted to get this issue in so any possible compatibility problems can be determined with this gem and ruby-lsp 0.22.0.

**Comment by vinistock** [comment]
Thank you for the report. We always keep a tight constraint because the add-on API is still going through a lot of breaking changes as we understand how to make the most out of it.

Whenever there are new breaking changes, we typically get to them within a few days.

#529 will addresses the breaking changes and we need #527 and #530 to cut a release.

**Comment by vinistock** [comment]
This is completed since [v0.3.27](https://github.com/Shopify/ruby-lsp-rails/releases/tag/v0.3.27).
